### PR TITLE
Design tweaks, fixed & added animations

### PR DESCRIPTION
**Pull request by noahdigesu**
- Centered titles & filters because it made more sense seeing the flow of the website.
- Changed the `linear-gradient` background to a `::before` pseudo-element for `.button_tags` so hover animations are a simpler, cleaner & better supported.
- Fixed the search bar & search bar icon.
- Added an animation that makes the `card` "pop in" instead of it appearing abruptly when clicking on the "Aléatoire" button.
- Added an animation that makes the `display-card-container` fade-in & fixed the background that didn't cover the whole screen.

_PS_ : It's my first time I'm contributing to an open source project that's not mine, looking forward to any constructive criticism about my code / commits / etc. (French or English is fine by me).
_PPS_ : Sorry if the code indentation has changed, I set up my editor so it automatically formats files on save, should I change that ? Or is it not bothering ?

### CODE REVIEW

**Comment by anisayari** [comment]
Thank you ! Can you please add image before / after in your PR message. Also please **push on branch test** not on branch main. After reviewing your commit they will pushed to main. 

thank you

**Comment by anisayari** [comment]
@noahdigesu can you pull on test branch please ? this work is really valuable thank you

**Comment by noahdigesu** [comment]
@anisayari will do soon, I'm watching the football match right now, my country is playing 😬

**Comment by noahdigesu** [comment]
done during the break ! :)

**Pull request closed without merging**
