### PR TITLE
filters are now part of a form and and uses search params

### PR DESCRIPTION
**Pull request by Valloa**
Filters are part of a form and using form inputs instead of buttons.
The form values are also used as search params.

Styles and JS updated accordingly.
Minors visual changes in order to increase readability and confort.

Old filters:
form old

Update:
form new

### CODE REVIEW

**Review by anisayari — COMMENTED** [review]
Can you please add more details about what you did exactly please ? Your PR decriptions is empty

**Review by anisayari — COMMENTED** [review]
Can you please add more details about what you did exactly please ? Your PR decriptions is empty

**Comment by Valloa** [comment]
Added the description.

**Comment by anisayari** [comment]
> Added the description.

Thank you. Did you change any front style ? If you changed anything visuals. Can you please provide images of your changes ? thank you

**Comment by Valloa** [comment]
Updated

**Comment by anisayari** [comment]
Hello, je peux pas merger sur main. 
Je vais devoir annuler la PR sur test. 

Il y a 2 problèmes : 

- il n'y a plus de shuffle à chaque actualisation
- certaines categories de filtre ne fonctionnent plus comme 'IA & Machine Learning'

**Pull request merged**
